<?php

// Includes
//module_load_include('inc', 'crp_cp', 'crp_cp');

/**
 * Implements hook_menu().
 */
function site_cp_menu() {
  $items['cp/cloudcast-legacy'] = array(
    'title' => 'Control Panel: Cloudcast Legacy Fix',
    'description' => 'Control Panel: Colors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_cp_legacy_image_form'),
    'access arguments' => array('access cc legacy image'),
    //'file' => 'forms/site_cp.colors.form.inc',
    'type' => MENU_CALLBACK,
  );  
  $items['cp/colors'] = array(
    'title' => 'Control Panel: Colors',
    'description' => 'Control Panel: Colors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_cp_colors_form'),
    'access arguments' => array('access control panel'),
    'file' => 'forms/site_cp.colors.form.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Form constructor
 */
function site_cp_legacy_image_form($form, &$form_state) {  
  $form['warning'] = array(
    '#markup' => '<b style="color:red;">Clicking this button will generate cloudcast legacy image thumbnails. Heavy processing, let it run until finished. <br /><br />ONLY NEEDS TO BE RUN ONCE. IGNORE ERROR MSGS RETURNED. DO NOT RUN THIS ON A PRODUCTION SITE.</b><br /><br />'
  );
  $form['password'] = array(
    '#type' => 'textfield',
    '#title' => 'Password',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Generate Legacy Image Thumbnails',
  );
  return $form;    
}

/**
 * Form validation
 */
function site_cp_legacy_image_form_validate($form, &$form_state) {
  if ($form_state['values']['password'] != 'GENERATE') {
    form_set_error('password', t('Incorrect password. Please try again.'));
  }
}

/**
 * Form submit
 */
function site_cp_legacy_image_form_submit($form, &$form_state) {     
  // Surpress php strict warning errors.
  // In general this is very bad practice, but these error msgs here 
  // are irrelevant to the fix here, which is basically a hack.
  error_reporting(E_ALL ^ E_STRICT);
  
  $fids = db_query("SELECT field_show_vod_fid FROM {field_data_field_show_vod}")->fetchAll();
  if (isset($fids)) {
    foreach($fids as $fid) {
      $file = file_load($fid->field_show_vod_fid);
      $return[] = drupal_render(media_get_thumbnail_preview($file, true));
    }
  }  
  return $return;
  drupal_set_message('Legacy Cloudcast image thumbnails generated!');
}

/**
 * Implements hook_permission().
 */
function site_cp_permission() {
  return array(
    'access control panel' => array(
      'title' => t('Access Control Panel'),
      'description' => t('Access Control Panel. ** Grant to Trusted Admin Users Only **'),
    ),
    'access cc legacy image' => array(
      'title' => t('Access Cloudcast Legacy Image Processor'),
      'description' => t('Access to run Cloudcast Legacy Image Processor ** Grant to Trusted Admin Users Only **'),
    ),
  );
}

/**
 * Implements hook_custom_theme().
 * Switch theme based on paths
 */
function site_cp_custom_theme() {
  // 
  if (arg(0) == 'cp') {
    return 'seven';
  }
}

/**
 * Helper function to get colors.
 */
function site_cp_colors_get() {
  $colors = db_query('SELECT * FROM {site_cp_colors}')->fetchAll();
  
  $colors_array = array();
  foreach($colors as $color) {
    $colors_array[$color->name] = $color->value;
  }
  
  return $colors_array;
}
