<?php

/**
 * Implements hook_feeds_before_update()
 */
function media_cloudcast_feeds_after_save(FeedsSource $source, $entity, $item, $entity_id) {
  $file_id = $entity->field_show_vod[LANGUAGE_NONE][0]['fid'];
  $file = file_load($file_id);
  $image_uri = 'media-cloudcast/' . $file->filename  . '.jpg';
    
  if (!file_exists(file_build_uri($image_uri))) {
    drupal_render(media_get_thumbnail_preview($file));
  }
}
