<?php
/**
 * @file
 * Customizations for Site Wrapper
 */
 
//
module_load_include('inc', 'site_wrapper', 'site_wrapper');
module_load_include('inc', 'site_wrapper', 'site_wrapper.user_menu');

/**
 * Implements hook_block_info().
 */
function site_wrapper_block_info() {  
  
  $blocks['site_wrapper_sitename'] = array(
    'info' => t('Site Name [Site Wrapper]'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => '0',
  );
  
  $blocks['site_wrapper_user_menu'] = array(
    'info' => t('User Menu [Site Wrapper]'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => '0',
  );
  
  $blocks['site_wrapper_logo'] = array(
    'info' => t('Site Logo [Site Wrapper]'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => '0',
  );
  
  $blocks['site_wrapper_main_menu'] = array(
    'info' => t('Main Menu [Site Wrapper]'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => '0',
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 * @see site_wrapper.inc 
 */
function site_wrapper_block_view($delta = '') {
  $block = array();

  switch ($delta) {  
    case 'site_wrapper_sitename':
      $sitename = l(t(variable_get('site_name')), '<front>', array('attributes' => array('class' => array('name navbar-brand'))));
    
    
      //$block['content'] = '<a class="name navbar-brand" href="#" title="Home">' . variable_get('site_name') . '</a>';
      $block['content']  = $sitename;
      break;
    
    case 'site_wrapper_user_menu':
      $block['content'] = site_wrapper_user_menu();
      break;
    
    
    //create block for site logo
    case 'site_wrapper_logo':    
      $logo = '<a href="/"><img src="' . theme_get_setting('logo') . '" /></a>';
    
      $block['content'] = $logo;
      break;
    
    //  
    case 'site_wrapper_main_menu':
    
    
    
      $block['content'] = _site_wrapper_main_menu_data_query();
      break;
    
  }
  
  
  return $block;
}

/**
 * Implements hook_theme().
 */
function site_wrapper_theme() {
  return array(
    'site_wrapper_main_menu' => array(
      'template' => 'templates/site-wrapper-main-menu',
    ),
  );
}



